config/routes.rb
require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username),
                                              ::Digest::SHA256.hexdigest(ENV['ADMIN_USERNAME'])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password),
                                                ::Digest::SHA256.hexdigest(ENV['ADMIN_PASSWORD']))
end if Rails.env.production?

Rails.application.routes.draw do
  mount Sidekiq::Web, at: '/sidekiq'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  mount Decidim::Core::Engine => '/'

  get 'admin/user_proposal_statistic_report/:slug', to: 'decidim/govbr/user_proposals_statistic_settings#export_user_data', as: 'user_proposal_statistic_report'

  # These two routes are not present anywhere in the product
  # Instead, it's meant to be used by an advanced admin directly on URL
  # This is going to be removed once admin front-end is finished
  get(
    'admin/user_proposal_statistic_report_force_refresh/:slug',
    to: 'decidim/govbr/user_proposals_statistic_settings#force_refresh',
    as: 'user_proposal_statistic_report_force_refresh'
  )
  get(
    'admin/user_proposal_statistic_report_create/:slug',
    to: 'decidim/govbr/user_proposals_statistic_settings#create',
    as: 'user_proposal_statistic_report_create'
  )

  patch '/update_status_comment/:id/', to: 'decidim/comments/comments#update_status', as: 'update_comment_status'

  resources :assemblies, param: :slug, only: [] do
    resources :media, only: :index, controller: 'decidim/assemblies/media'
  end

  resources :participatory_processes, param: :slug, only: [], path: :processes do
    resources :media, only: :index, controller: 'decidim/participatory_processes/media'
  end

  scope :admin do
    resources :assemblies, param: :slug, only: [] do
      resources :partners, except: [:show], controller: 'decidim/assemblies/admin/partners'
      resources :media_links, except: [:show], controller: 'decidim/assemblies/admin/media_links'
    end
  end

  scope :admin do
    resources :participatory_processes, param: :slug, only: [] do
      resources :partners, except: [:show], controller: 'decidim/participatory_processes/admin/partners'
      resources :media_links, except: [:show], controller: 'decidim/participatory_processes/admin/media_links'
    end
  end
end

app/models/decidim/meetings/meeting.rb
# frozen_string_literal: true

module Decidim
  module Meetings
    # The data store for a Meeting in the Decidim::Meetings component. It stores a
    # title, description and any other useful information to render a custom meeting.
    class Meeting < Meetings::ApplicationRecord
      include Decidim::Resourceable
      include Decidim::HasAttachments
      include Decidim::HasAttachmentCollections
      include Decidim::HasComponent
      include Decidim::HasReference
      include Decidim::ScopableResource
      include Decidim::HasCategory
      include Decidim::Followable
      include Decidim::Comments::CommentableWithComponent
      include Decidim::Comments::HasAvailabilityAttributes
      include Decidim::Searchable
      include Decidim::Traceable
      include Decidim::Loggable
      include Decidim::Forms::HasQuestionnaire
      include Decidim::Paddable
      include Decidim::ActsAsAuthor
      include Decidim::Reportable
      include Decidim::Authorable
      include Decidim::TranslatableResource
      include Decidim::Publicable
      include Decidim::FilterableResource

      TYPE_OF_MEETING = %w(in_person online hybrid).freeze
      REGISTRATION_TYPE = %w(registration_disabled on_this_platform on_different_platform).freeze

      translatable_fields :title, :description, :location, :location_hints, :closing_report, :registration_terms

      has_many :registrations, class_name: "Decidim::Meetings::Registration", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_many :invites, class_name: "Decidim::Meetings::Invite", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_many :services, class_name: "Decidim::Meetings::Service", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_one :agenda, class_name: "Decidim::Meetings::Agenda", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_one :poll, class_name: "Decidim::Meetings::Poll", foreign_key: "decidim_meeting_id", dependent: :destroy
      has_many(
        :public_participants,
        -> { merge(Registration.public_participant) },
        through: :registrations,
        class_name: "Decidim::User",
        foreign_key: :decidim_user_id,
        source: :user
      )

      enum iframe_access_level: [:all, :signed_in, :registered], _prefix: true
      enum iframe_embed_type: [:none, :embed_in_meeting_page, :open_in_live_event_page, :open_in_new_tab], _prefix: true

      component_manifest_name "meetings"

      validates :title, presence: true

      geocoded_by :address

      scope :published, -> { where.not(published_at: nil) }
      scope :past, -> { where(arel_table[:end_time].lteq(Time.current)) }
      scope :upcoming, -> { where(arel_table[:end_time].gteq(Time.current)) }
      scope :withdrawn, -> { where(state: "withdrawn") }
      scope :except_withdrawn, -> { where.not(state: "withdrawn").or(where(state: nil)) }
      scope :with_availability, lambda { |state_key|
        case state_key
        when "withdrawn"
          withdrawn
        else
          except_withdrawn
        end
      }
      scope_search_multi :with_any_date, [:upcoming, :past]
      scope :with_any_space, lambda { |*target_space|
        target_spaces = target_space.compact.compact_blank

        return self if target_spaces.blank? || target_spaces.include?("all")

        joins(:component).where(
          decidim_components: { participatory_space_type: target_spaces.map(&:classify) }
        )
      }

      scope :visible_for, lambda { |user|
        (all.distinct if user&.admin?) ||
          if user.present?
            spaces = Decidim.participatory_space_registry.manifests.filter_map do |manifest|
              table_name = manifest.model_class_name.constantize.try(:table_name)
              next if table_name.blank?

              {
                name: table_name.singularize,
                class_name: manifest.model_class_name
              }
            end
            user_role_queries = spaces.map do |space|
              roles_table = "#{space[:name]}_user_roles"
              next unless connection.table_exists?(roles_table)

              "SELECT decidim_components.id FROM decidim_components
              WHERE CONCAT(decidim_components.participatory_space_id, '-', decidim_components.participatory_space_type)
              IN
              (SELECT CONCAT(#{roles_table}.#{space[:name]}_id, '-#{space[:class_name]}')
              FROM #{roles_table} WHERE #{roles_table}.decidim_user_id = ?)
              "
            end

            query = "
              decidim_meetings_meetings.private_meeting = ?
              OR decidim_meetings_meetings.transparent = ?
              OR decidim_meetings_meetings.id IN (
                SELECT decidim_meetings_registrations.decidim_meeting_id FROM decidim_meetings_registrations WHERE decidim_meetings_registrations.decidim_user_id = ?
              )
              OR decidim_meetings_meetings.decidim_component_id IN (
                SELECT decidim_components.id FROM decidim_components
                WHERE CONCAT(decidim_components.participatory_space_id, '-', decidim_components.participatory_space_type)
                IN
                  (SELECT CONCAT(decidim_participatory_space_private_users.privatable_to_id, '-', decidim_participatory_space_private_users.privatable_to_type)
                  FROM decidim_participatory_space_private_users WHERE decidim_participatory_space_private_users.decidim_user_id = ?)
              )
            "
            if user_role_queries.any?
              query = "#{query} OR decidim_meetings_meetings.decidim_component_id IN
                (#{user_role_queries.compact.join(" UNION ")})
              "
            end

            where(Arel.sql(query).to_s, false, true, user.id, user.id, *user_role_queries.compact.map { user.id }).published.distinct
          else
            published.visible
          end
      }

      scope :visible, -> { where("decidim_meetings_meetings.private_meeting != ? OR decidim_meetings_meetings.transparent = ?", true, true) }

      scope :authored_by, ->(author) { where(decidim_author_id: author) }

      scope_search_multi :with_any_type, TYPE_OF_MEETING.map(&:to_sym)

      TYPE_OF_MEETING.each do |type|
        scope type.to_sym, -> { where(type_of_meeting: type.to_sym) }
        scope "not_#{type}".to_sym, -> { where.not(type_of_meeting: type.to_sym) }
      end

      searchable_fields({
                          scope_id: :decidim_scope_id,
                          participatory_space: { component: :participatory_space },
                          A: :title,
                          D: [:description, :address],
                          datetime: :start_time
                        },
                        index_on_create: ->(meeting) { meeting.visible? && meeting.published? },
                        index_on_update: ->(meeting) { meeting.visible? && meeting.published? })

      # we create a salt for the meeting only on new meetings to prevent changing old IDs for existing (Ether)PADs
      before_create :set_default_salt

      def self.participants_iframe_embed_types
        iframe_embed_types.except(:open_in_live_event_page)
      end

      # Return registrations of a particular meeting made by users representing a group
      def user_group_registrations
        registrations.where.not(decidim_user_group_id: nil)
      end

      # Returns the presenter for this author, to be used in the views.
      # Required by ActsAsAuthor.
      def presenter
        Decidim::Meetings::MeetingPresenter.new(self)
      end

      def self.log_presenter_class_for(_log)
        Decidim::Meetings::AdminLog::MeetingPresenter
      end

      def can_be_joined_by?(user)
        !closed? && registrations_enabled? && can_participate?(user)
      end

      def can_register_invitation?(user)
        !closed? && registrations_enabled? &&
          can_participate_in_space?(user) && user_has_invitation_for_meeting?(user)
      end

      def closed?
        closed_at.present?
      end

      def past?
        end_time < Time.current
      end

      def emendation?
        false
      end

      def has_available_slots?
        return true if available_slots.zero?

        (available_slots - reserved_slots) > registrations.count
      end

      def remaining_slots
        available_slots - reserved_slots - registrations.count
      end

      def subscribers_count
        registrations.count
      end

      def has_registration_for?(user)
        registrations.where(user: user).any?
      end

      def maps_enabled?
        component.settings.maps_enabled?
      end

      # Public: Overrides the `accepts_new_comments?` CommentableWithComponent concern method.
      def accepts_new_comments?
        commentable? && !component.current_settings.comments_blocked && comments_allowed?
      end

      # Public: Overrides the `allow_resource_permissions?` Resourceable concern method.
      def allow_resource_permissions?
        component.settings.resources_permissions_enabled
      end

      # Public: Overrides the `comments_have_alignment?` Commentable concern method.
      def comments_have_alignment?
        true
      end

      # Public: Overrides the `comments_have_votes?` Commentable concern method.
      def comments_have_votes?
        true
      end

      # Public: Override Commentable concern method `users_to_notify_on_comment_created`
      def users_to_notify_on_comment_created
        followers
      end

      def can_participate?(user)
        can_participate_in_space?(user) && can_participate_in_meeting?(user)
      end

      def current_user_can_visit_meeting?(user)
        Decidim::Meetings::Meeting.visible_for(user).exists?(id: id)
      end

      def iframe_access_level_allowed_for_user?(user)
        case iframe_access_level
        when "all"
          true
        when "signed_in"
          user.present?
        else
          has_registration_for?(user)

app/controllers/concerns/decidim/meetings/component_filterable.rb
# frozen_string_literal: true

require "active_support/concern"

module Decidim
  module Meetings
    # A controller concern to specify default filter parameters for the
    # controller resources within a meetings component.
    module ComponentFilterable
      extend ActiveSupport::Concern

      included do
        private

        def default_filter_params
          {
            search_text_cont: "",
            with_any_date: "upcoming",
            activity: "all",
            with_availability: "",
            with_any_scope: default_filter_scope_params,
            with_any_category: default_filter_category_params,
            with_any_state: nil,
            with_any_origin: default_filter_origin_params,
            with_any_type: default_filter_type_params
          }
        end
      end
    end
  end
end

app/controllers/decidim/meetings/meetings_controller.rb
# frozen_string_literal: true
require 'date'

module Decidim
  module Meetings
    # Exposes the meeting resource so users can view them
    class MeetingsController < Decidim::Meetings::ApplicationController
      include FilterResource
      include Filterable
      include ComponentFilterable
      include Flaggable
      include Withdrawable
      include FormFactory
      include Paginable

      helper Decidim::WidgetUrlsHelper
      helper Decidim::ResourceVersionsHelper
      helper Decidim::ShortLinkHelper
      helper_method :meetings, :meeting, :registration, :search


      def new
        enforce_permission_to :create, :meeting

        @form = meeting_form.instance
      end

      def create
        enforce_permission_to :create, :meeting

        @form = meeting_form.from_params(params, current_component: current_component)

        CreateMeeting.call(@form) do
          on(:ok) do |meeting|
            flash[:notice] = I18n.t("meetings.create.success", scope: "decidim.meetings")
            redirect_to meeting_path(meeting)
          end

          on(:invalid) do
            flash.now[:alert] = I18n.t("meetings.create.invalid", scope: "decidim.meetings")
            render action: "new"
          end
        end
      end

      def index

        return unless search.result.blank? && params.dig("filter", "date") != %w(past)

        @past_meetings ||= search_with(filter_params.merge(with_any_date: %w(past)))

        if @past_meetings.result.present?
          params[:filter] ||= {}
          params[:filter][:with_any_date] = %w(past)
          @forced_past_meetings = true
          @search = @past_meetings
        end
      end

      def show
        raise ActionController::RoutingError, "Not Found" unless meeting

        return if meeting.current_user_can_visit_meeting?(current_user)

        flash[:alert] = I18n.t("meeting.not_allowed", scope: "decidim.meetings")
        redirect_to(ResourceLocatorPresenter.new(meeting).index)
      end

      def edit
        enforce_permission_to :update, :meeting, meeting: meeting

        @form = meeting_form.from_model(meeting)
      end

      def update
        enforce_permission_to :update, :meeting, meeting: meeting

        @form = meeting_form.from_params(params)

        UpdateMeeting.call(@form, current_user, meeting) do
          on(:ok) do |meeting|
            flash[:notice] = I18n.t("meetings.update.success", scope: "decidim.meetings")
            redirect_to Decidim::ResourceLocatorPresenter.new(meeting).path
          end

          on(:invalid) do
            flash.now[:alert] = I18n.t("meetings.update.invalid", scope: "decidim.meetings")
            render :edit
          end
        end
      end

      def withdraw
        enforce_permission_to :withdraw, :meeting, meeting: meeting

        WithdrawMeeting.call(@meeting, current_user) do
          on(:ok) do
            flash[:notice] = I18n.t("meetings.withdraw.success", scope: "decidim")
            redirect_to Decidim::ResourceLocatorPresenter.new(@meeting).path
          end
          on(:invalid) do
            flash[:alert] = I18n.t("meetings.withdraw.error", scope: "decidim")
            redirect_to Decidim::ResourceLocatorPresenter.new(@meeting).path
          end
        end
      end

      private

      def meeting
        @meeting ||= Meeting.not_hidden.where(component: current_component).find_by(id: params[:id])
      end

      def meetings
        is_past_meetings = params.dig("filter", "with_any_date")&.include?("past")
        @meetings ||= paginate(search.result.order(start_time: is_past_meetings ? :desc : :asc))
      end

      def registration
        @registration ||= meeting.registrations.find_by(user: current_user)
      end

      def search_collection
        Meeting.where(component: current_component).published.not_hidden.visible_for(current_user).with_availability(
          filter_params[:with_availability]
        ).includes(
          :component,
          attachments: :file_attachment
        )
      end

      def meeting_form
        form(Decidim::Meetings::MeetingForm)
      end


    end
  end
end

app/views/decidim/meetings/meetings/_calendar_modal.html.erb
<button class="br-button" data-open="calendarShare">
  <%= t("add_to_calendar", scope: "decidim.meetings.meetings.calendar_modal" ) %>
  <i class="fa-regular fa-calendar m-2"></i>
</button>

<div class="reveal" id="calendarShare" data-reveal>
  <div class="reveal__header">
    <h2 class="reveal__title"><%= t("add_to_calendar", scope: "decidim.meetings.meetings.calendar_modal") %></h2>
    <button class="close-button" data-close aria-label="<%= t("close_window", scope: "decidim.meetings.meetings.calendar_modal") %>" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <ul>
    <li>
      <%= link_to t("outlook", scope: "decidim.meetings.meetings.calendar_modal"), ics_url %>
    </li>
    <li>
      <%= link_to t("apple", scope: "decidim.meetings.meetings.calendar_modal"), ics_url %>
    </li>
    <li>
      <%= link_to t("google", scope: "decidim.meetings.meetings.calendar_modal"), google_url, target: "_blank" %>
    </li>
  </ul>
</div>

app/views/decidim/meetings/meetings/_count.html.erb
<%= t(".meetings_count", count: search.result.count) %>

app/views/decidim/meetings/meetings/_datetime.html.erb
<div class="card__datetime">
  <div class="card__datetime__date">
    <%= l meeting.start_time, format: "%d" %> <span class="card__datetime__month"><%= l meeting.start_time, format: "%B %Y" %></span>
  </div>
  <div class="card__datetime__time">
    <%= meeting.start_time.strftime("%H:%M") %> - <%= meeting.end_time.strftime("%H:%M") %>
  </div>
</div>

app/views/decidim/meetings/meetings/_filters.html.erb
<%= render partial: "decidim/shared/filter_form_help", locals: { skip_to_id: "meetings" } %>

<%= filter_form_for filter do |form| %>
  <div class="filters__section">
    <div class="filters__search">
      <div class="input-group">
        <%= form.search_field :search_text_cont, label: false, class: "input-group-field", placeholder: t(".search"), title: t(".search"), "aria-label": t(".search"), data: { disable_dynamic_change: true } %>
        <div class="input-group-button">
          <button type="submit" class="button" aria-controls="meetings">
            <%= icon "magnifying-glass", aria_label: t(".search"), role: "img" %>
          </button>
        </div>
      </div>
    </div>
  </div>

  <%= form.hidden_field "with_availability", value: params.dig("filter", "with_availability") %>

  <% unless @forced_past_meetings %>
    <%= form.collection_radio_buttons :with_any_date, filter_date_values, :first, :last, legend_title: t(".date") %>
  <% end %>

  <%= form.check_boxes_tree :with_any_type, filter_type_values, legend_title: t(".type") %>

  <% if current_component.has_subscopes? %>
    <%= form.check_boxes_tree :with_any_scope, filter_scopes_values, legend_title: t(".scope") %>
  <% end %>

  <% if current_component.categories.any? %>
    <%= form.check_boxes_tree :with_any_category, filter_categories_values, legend_title: t(".category") %>
  <% end %>

  <% if component_settings.creation_enabled_for_participants? %>
    <%= form.check_boxes_tree :with_any_origin, filter_origin_values, legend_title: t(".origin") %>
  <% end %>

  <% if current_user %>
    <%= form.collection_radio_buttons :activity, activity_filter_values, :first, :last, { legend_title: t(".activity") }, "aria-controls": "meetings" %>
  <% end %>
<% end %>

app/views/decidim/meetings/meetings/_filters_small_view.html.erb
<div class="statistics-controls">
  <button data-open="filter-box" aria-controls="filter-box" aria-haspopup="dialog">
    <span class="meetings__button-circle button-container-style">
      <i class="fas fa-sliders-h size-icon-filter"></i>
    </span>
  </button>
</div>

<div class="br-reveal" id="filter-box" data-reveal role="dialog" aria-modal="true" aria-labelledby="filter-box-label">
  <div class="reveal__header">
    <h3 id="filter-box-label" class="reveal__title"><%= t ".filter_by" %>:</h3>
    <button class="close-button" data-close aria-label="<%= t(".close_modal") %>" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="filters">
    <%= render partial: "filters" %>
  </div>
</div>

app/views/decidim/meetings/meetings/index.html.erb
<%= render partial: "decidim/shared/component_announcement" %>

<% if current_component.settings.maps_enabled? && search.result.not_online.exists? %>
  <%= cell "decidim/meetings/meetings_map", search.result %>
<% end %>

<div class="br-container-lg">
<div class="row columns">
  <div class="title-action">
    

    <% if allowed_to?(:create, :meeting) %>
      <%= action_authorized_link_to :create, new_meeting_path, class: "title-action__action button small", data: { "redirect_url" => new_meeting_path } do %>
        <%= t("new_meeting", scope: "decidim.meetings.meetings.index") %>
        <%= icon "plus", role: "img", "aria-hidden": true %>
      <% end %>
    <% end %>
  </div>
</div>

<div class="br-row">
  <div class="columns mediumlarge-4 large-3">
    <% if browser.mobile? %>
        <div class="meetings-button__container">
          <%= render partial: "filters_small_view" %>
        </div>
    <% end %>
    <div class="card card--secondary show-for-mediumlarge ">
      <%= render partial: "filters" %>
    </div>
  </div>
  <div id="meetings" class="columns mediumlarge-8 large-9" aria-live="polite">

    <%= render partial: "meetings" %>
  </div>
</div>
</div>

app/views/decidim/meetings/meetings/show.html.erb
<% provide(:title, present(meeting).title) %>

<% add_decidim_meta_tags({
  title: present(meeting).title,
  description: present(meeting).description,
  url: meeting_url(meeting.id)
}) %>

<%
edit_link(
  resource_locator(meeting).edit,
  :update,
  :meeting,
  meeting: meeting
)
%>
<div class="br-container-lg">
    <div class="view-header">
    <div class="m-bottom">
        <%= link_to meetings_path, class: "small hollow js-back-to-list" do %>
        <%= icon "chevron-left", class: "icon--small", role: "img", "aria-hidden": true %>
        <%= t(".back") %>
        <% end %>
    </div>

    <h2 class="page-title"><%= present(meeting).title(links: true, html_escape: true ) %></h2>

    <%= cell "decidim/author", author_presenter_for(meeting.normalized_author), has_actions: true, from: meeting, context: { extra_classes: ["author-data--small"] } %>

    </div>
    <div class="row row-counter">
    <div class="columns section view-side mediumlarge-4 mediumlarge-push-8
                large-3 large-push-9">

        <% if allowed_to?(:update, :meeting, meeting: meeting) %>
        <%= link_to t(".edit_meeting"), edit_meeting_path(meeting), class: "button secondary hollow expanded button-sc button--icon follow-button" %>
        <% end %>

        <% if allowed_to?(:close, :meeting, meeting: meeting) %>
        <% caption =  meeting.closed? ? t(".edit_close_meeting") : t(".close_meeting") %>
        <%= link_to caption, edit_meeting_meeting_close_path(meeting_id: meeting.id, id: meeting.id), class: "button hollow expanded button-sc button--icon follow-button" %>
        <% end %>

        <div class="card extra">
        <div class="card__content">
            <%= cell("decidim/date_range", { start: meeting.start_time, end: meeting.end_time }) %>

            <%= cell "decidim/meetings/join_meeting_button", meeting, big_button: true, show_remaining_slots: true %>
        </div>
        <% if meeting.closed? && meeting.closing_visible? %>
            <% double = meeting.has_contributions? && meeting.has_attendees? %>
            <div class="card card--secondary extra definition-data">
            <% if meeting.has_contributions? %>
                <div class="definition-data__item <%= "definition-data__item--double" if double %>">
                <span class="definition-data__title"><%= t(".contributions") %></span>
                <span class="definition-data__number"><%= meeting.contributions_count %></span>
                </div>
            <% end %>
            <% if meeting.has_attendees? %>
                <div class="definition-data__item <%= "definition-data__item--double" if double %>">
                <span class="definition-data__title"><%= t(".attendees") %></span>
                <span class="definition-data__number"><%= meeting.attendees_count %></span>
                </div>
            <% end %>
            <% if meeting.attending_organizations.present? %>
                <div class="definition-data__item">
                <span class="definition-data__title"><%= t(".organizations") %></span>
                <span class="definition-data__text"><%= simple_format(meeting.attending_organizations) %></span>
                </div>
            <% end %>
            </div>
        <% end %>
        </div>

        <% if registration.present? && registration.meeting.component.settings.registration_code_enabled %>
        <div class="card extra">
            <div class="card__content">
                <div class="registration_code">
                <span><%= registration_code_help_text %></span>
                <span><strong><%= registration.code %></strong></span>
                <div class="text-small"><%= validation_state_for(registration) %></div>
                </div>
            </div>
        </div>
        <% end %>

        <% if meeting.services.any? %>
        <div class="card card--list">
            <% meeting.services.each do |service| %>
            <div class="card--list__item">
                <div class="card--list__text card--list__text--top">
                <%= icon "actions", class: "card--list__icon alert", role: "img", "aria-hidden": true %>
                <div>
                    <h3 class="card--list__heading heading-small"><%= translated_attribute(service["title"]) %></h3>
                    <span class="text-medium"><%= translated_attribute(service["description"]) %></span>
                </div>
                </div>
            </div>
            <% end %>
        </div>
        <% end %>

        <%= resource_reference(meeting) %>
        <%= resource_version(meeting, versions_path: meeting_versions_path(meeting)) %>
        <%= render partial: "decidim/shared/share_modal" %>
        <%= embed_modal_for meeting_widget_url(meeting, format: :js) %>
        <%= render partial: "calendar_modal", locals: { ics_url: calendar_meeting_url(meeting), google_url: google_calendar_event_url(meeting) } %>
    </div>
    <div class="columns mediumlarge-8 mediumlarge-pull-4">
        <div class="section">
        <% if meeting.private_meeting? %>
            <span class="<%= meeting_type_badge_css_class("private") %> label proposal-status">
            <%= t("private_meeting", scope: "decidim.meetings.types") %>
            </span>
        <% end %>
        <% if meeting.private_meeting? and meeting.transparent? %>
            <span class="<%= meeting_type_badge_css_class("transparent") %> label proposal-status">
            <%= t("transparent", scope: "decidim.meetings.types") %>
            </span>
        <% end %>
        <% if meeting.withdrawn? %>
            <span class="<%= meeting_type_badge_css_class("withdraw") %> label proposal-status">
            <%= t("withdraw", scope: "decidim.meetings.types") %>
            </span>
        <% end %>
        <%= render_meeting_body(@meeting) %>

        <% if meeting.maps_enabled? && !meeting.online_meeting? %>
            <%= render partial: "decidim/shared/static_map", locals: { icon_name: "meetings", geolocalizable: meeting } %>
        <% end %>

        <% unless meeting.in_person_meeting? || meeting.withdrawn? %>
            <%= cell "decidim/meetings/online_meeting_link", meeting %>
        <% end %>

        <%= render partial: "decidim/shared/tags", locals: { resource: meeting, tags_class_extra: "tags--meeting" } %>
        </div>

        <% if meeting.agenda.present? && meeting.agenda.visible? %>
        <%= render "meeting_agenda" %>
        <% end %>

        <%= cell "decidim/meetings/public_participants_list", meeting %>

        <% if !meeting.closed? && meeting.user_group_registrations.any? %>
        <% user_group_ids = meeting.user_group_registrations.user_group_ids %>
        <div class="section">
            <h4 class="section-heading"><%= t(".organizations") %></h4>
            <div class="card card--list">
            <% Decidim::UserGroup.where(id: user_group_ids).each do |group| %>
                <div class="card--list__item">
                <div class="card--list__text card--list__text--top">
                <%= cell "decidim/author", present(group) %>
                </div>
                </div>
            <% end %>
            </div>
        </div>
        <% end %>

        <% if meeting.closed? && meeting.closing_visible? %>
        <div class="section">
            <h3 class="section-heading"><%= t(".meeting_minutes") %></h3>
            <%= decidim_sanitize_editor translated_attribute meeting.closing_report %>
        </div>
        <% end %>

        <%= linked_resources_for meeting, :proposals, "proposals_from_meeting" %>
        <%= linked_resources_for meeting, :results, "meetings_through_proposals" %>
    </div>
    </div>
    <%= attachments_for meeting %>
    <%= comments_for meeting %>
    <%= pad_iframe_for meeting %>

    <%= cell("decidim/flag_modal", meeting) %>
</div>